export const skillMap: Record<string, Record<string, number>> = {
    Language: {
        Java: 90,
        JavaScript: 80,
        TypeScript: 90,
        HTML: 90,
        CSS: 90,
        'C/C++': 85,
        'C#': 70,
        Python: 70,
        Kotlin: 65,
        Dart: 65,
        SQL: 60,
        PHP: 50,
    },
    Server: {
        'Express.js': 85,
        Firebase: 85,
        'Flask(Python)': 50,
    },
    Front: {
        'React.js': 90,
        JQuery: 70,
        JavaFX: 75,
    },
    Embedded: {
        Arduino: 85,
        RaspBerryPi: 85,
        Nordic: 75,
        Stm32: 60,
    },
    Mobile: {
        'Android(Java)': 80,
        Flutter: 75,
        ReactNative: 70,
        Xamarin: 60,
    },
    Etc: {
        AfterEffect: 80,
        PhotoShop: 85,
        AdobeXD: 85,
        FIDO: 70,
        Docker: 60,
    },
};
